spring.application.name=tracker

spring.datasource.url=jdbc:mysql://localhost:3306/expensetracker?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root

# This property is used to tell Hibernate to alter the database tables as per entity mapping changes
spring.jpa.hibernate.ddl-auto=update