package com.suyos.tracker.dto;

import java.math.BigDecimal;
import java.time.LocalDate;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.suyos.tracker.model.Category;

import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.Digits;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.PastOrPresent;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Data Transfer Object for expense information.
 * 
 * This DTO is used to transfer expense data between the API layer and clients.
 * It provides a clean interface that decouples the internal entity structure
 * from the external API contract. JSON property annotations ensure consistent
 * field naming in API responses.
 * 
 * @author Joel Salazar
 * @version 1.0
 * @since 1.0
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ExpenseDTO {
    
    /**
     * Unique identifier for the expense.
     * 
     * Null for new expenses being created, populated for existing expenses.
     * No validation required as this field is auto-generated by the database.
     */
    @JsonProperty("id")
    private Long id;

    /**
     * Descriptive text explaining what the expense was for.
     * 
     * Must not be blank and has a maximum length to ensure meaningful
     * descriptions while preventing excessively long input.
     * Examples: "Grocery shopping", "Gas for car", "Monthly rent"
     */
    @NotBlank(message = "Description is mandatory")
    @Size(max = 255, message = "Description must not exceed 255 characters")
    @JsonProperty("description")
    private String description;

    /**
     * Monetary amount of the expense.
     * 
     * Uses BigDecimal to maintain precision for financial calculations
     * and avoid floating-point rounding errors. Must be at least $0.01
     * to represent actual monetary transactions.
     */
    @NotNull(message = "Amount is mandatory")
    @DecimalMin(value = "0.01", inclusive = true, message = "Amount must be at least $0.01")
    @Digits(integer = 7, fraction = 2, message = "Amount must have a maximum of 7 integer digits and 2 decimal places")
    @JsonProperty("amount")
    private BigDecimal amount;

    /**
     * Date when the expense occurred.
     * 
     * Represents the actual date of the expense, not when it was recorded.
     * Must not be in the future to ensure realistic expense tracking.
     */
    @NotNull(message = "Date is mandatory")
    @PastOrPresent(message = "Date cannot be in the future")
    @JsonProperty("date")
    private LocalDate date;

    /**
     * Category classification for the expense.
     * 
     * Used for organizing and filtering expenses by type.
     * Must be one of the predefined category values.
     */
    @NotNull(message = "Category is mandatory")
    @JsonProperty("category")
    private Category category;

}